### ISSUE TITLE
Missing layouts directory causes hugo error

### ISSUE THREAD

**Issue by stou** [spf13/HugoBasicExample#5]
stou@stou-mba:HugoBasicExample$ hugo server -w -t stou-dk-theme
0 draft content 
0 future content 
3 pages created 
6 tags created
2 categories created
in 57 ms
Watching for changes in /Users/stou/code/hugo/HugoBasicExample/content
ERROR: 2014/11/19 Walker:  lstat /Users/stou/code/hugo/HugoBasicExample/layouts: no such file or directory
Serving pages from /Users/stou/code/hugo/HugoBasicExample/public
Web Server is available at http://localhost:1313/
Press ctrl+c to stop
^C[2]stou@stou-mba:HugoBasicExample$ hugo version -v
INFO: 2014/11/19 Using config file: /Users/stou/code/hugo/HugoBasicExample/config.toml
Hugo Static Site Generator v0.13-DEV buildDate: 2014-11-19T23:13:09+07:00
stou@stou-mba:HugoBasicExample$

**Comment by anthonyfok** [comment]
Already fixed by @stou in Pull Request #6 and merged by @spf13.  (Thank you both!)
Closing this issue.
